#-------------------------------------------------------------------------------
# Unit Testing Dependencies
#-------------------------------------------------------------------------------

FetchContent_MakeAvailable(GoogleTest)

#-------------------------------------------------------------------------------
# Project Definition
#-------------------------------------------------------------------------------

project("${CMAKE_PROJECT_NAME} Unit Tests")

#-------------------------------------------------------------------------------
# Target Definition
#-------------------------------------------------------------------------------

set(TARGET_NAME "amxxpc.test")
add_executable("${TARGET_NAME}")

#-------------------------------------------------------------------------------
# Source Files
#-------------------------------------------------------------------------------

target_sources("${TARGET_NAME}"
  PRIVATE
    "src/cli/arguments.cpp"
    "src/cli/parser.cpp"
)

#-------------------------------------------------------------------------------
# Link Libraries
#-------------------------------------------------------------------------------

target_link_libraries("${TARGET_NAME}"
  PRIVATE
    "CmdLine::cmdline"
    "GTest::gtest_main"
)

#-------------------------------------------------------------------------------
# Unit Testing Configuration
#-------------------------------------------------------------------------------

# Discover and register all tests
gtest_discover_tests("${TARGET_NAME}")
