#-------------------------------------------------------------------------------
# Project Definition
#-------------------------------------------------------------------------------

project("Pawn Image")

#-------------------------------------------------------------------------------
# Target Definition
#-------------------------------------------------------------------------------

set(TARGET_NAME "pawnimage")
set(TARGET_ALIAS "PawnImage::pawnimage")

add_library("${TARGET_NAME}" INTERFACE)
add_library("${TARGET_ALIAS}" ALIAS "${TARGET_NAME}")

#-------------------------------------------------------------------------------
# Subdirectories
#-------------------------------------------------------------------------------

add_subdirectory("amx")
add_subdirectory("amxx")

#-------------------------------------------------------------------------------
# Link Libraries
#-------------------------------------------------------------------------------

target_link_libraries("${TARGET_NAME}"
  INTERFACE
    AMX::amx
    AMXX::amxx
)
